### ISSUE TITLE
Time-like component of four vector apparently in wrong position

### ISSUE THREAD

**Issue by vale981** [scikit-hep/pyhepmc#13]
Is there a reason to print-out the time-like component of a four vector as 4-th component?
https://github.com/scikit-hep/pyhepmc/blob/753072aed9914b3fa88ca03e9d02a1e19e68523b/src/bindings.cpp#L217

I am asking that just out of curiosity. Thank you for this nice package :)

**Comment by HDembinski** [comment]
Hi, yes, as a guideline, the output of `repr` should `eval` back to the value. FourVector accepts the time-like component as the forth entry, that's why the order is space-likes, time-like.
