### ISSUE TITLE
Is it deat or alive (or undead?)

### ISSUE THREAD

**Issue by DraTeots** [scikit-hep/pyhepmc#15]
Hi!

https://pypi.org/project/pyhepmc-ng/ says "pyhepmc-ng is actively developed" but in #14 stated: 

> Unfortunately, we couldn't turn this project into the default Python API for HepMC3, they have their own independent Python bindings. Therefore, I cannot offer much support.

Could you clarify the status of the project and if it is more on dead side, could you update pypi description to not to confuse new users. 

Thanks!

**Comment by HDembinski** [comment]
Hi @DraTeots sorry for the late reply. The project is not dead, but has not seen much development lately. I should definitely update the status on PyPI, thank you for the remark.
