### ISSUE TITLE
Set up a "hook" for Zenodo to mint DOIs

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/pyhepmc#19]
See for example https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content.

**Comment by HDembinski** [comment]
It is already set up since a while, I just haven't made a release yet. Is it urgent? I am going to make a release soon.

**Comment by eduardo-rodrigues** [comment]
No, no matter of urgency. I was doing some easy "admin" here and there and remembered this since I did not see the Zenodo badge in the README. If you got it ready I close this 👍.
