### ISSUE TITLE
Reading file using pyhepmc (pythia6_simple.dat)

### ISSUE THREAD

**Issue by amanmdesai** [scikit-hep/pyhepmc#51]
I tried to run the following commands: 

```python
import pyhepmc

# pyhepmc.open can read most HepMC formats using auto-detection
with pyhepmc.open("pythia6_simple.dat") as f:
    print(f)
    event = f.read()
    print(event)
```

(using the "pythia6_simple.dat" as given in tests/ )

I get the following output:

```
<pyhepmc._core.ReaderAscii object at 0x7ff53fefbbb0>
None.
```

**Comment by HDembinski** [comment]
@amanmdesai Thanks for reporting, but I cannot reproduce this. Which version of pyhepmc have you installed?

**Comment by amanmdesai** [comment]
Hi, Sorry. 
I tried to run the commands now and it seems it was an issue on my end. Commands work as expected.

Thanks.
