### ISSUE TITLE
Use `open` without `with`

### ISSUE THREAD

**Issue by kkauder** [scikit-hep/pyhepmc#67]
I'd like to do something like this:
```
f = pyhepmc.open("../../tests/pythia6_simple.dat")
event = f.read()
```
(Reason being that I want to stick `f` into an array with other open file handles and hand them off to a different method). 

But this crashes with
```
AttributeError: '_GeneratorContextManager' object has no attribute 'read'
```

**Comment by HDembinski** [comment]
This has been implemented in the meantime. I forgot to close this.
