### ISSUE TITLE
numpy is not listed as dependency

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhepmc#9]
Hi,

finally I get to try out this packahe. When installing pyhepmc in a new venv, where numpy is not yet installed, importing `pyhepmc_ng` fails. Maybe it should  be added to the list of dependencies in`setup.py`? Happy to add a PR.

**Comment by HDembinski** [comment]
I cannot confirm this. It works fine for me.

**Comment by HDembinski** [comment]
Make sure you use a clean fresh clone without any debris left over from a previous build, then it should work. `__init__.py` used to import numpy, but not anymore. If you want to hack/test pyhepmc, you should install the requirements.txt, as described in the README.

**Comment by lukasheinrich** [comment]
Hi, i'm using the version from pypi (pyhepmc-ng==0.4.2) installed via `pip`. Is there some other version I should be using?

```
>>> import pyhepmc_ng
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lukasheinrich/Code/analysis/hepmc/venv/lib/python2.7/site-packages/pyhepmc_ng/__init__.py", line 3, in <module>
    import numpy as np
ImportError: No module named numpy
```

(this does use python 2.7, since it's a constraint from other code I do not have control over, if this is a deal-breaker, probably it should still fail but with another message)

**Comment by HDembinski** [comment]
Ah! Thanks for the quick follow up. I need to update the PyPI version then, I will do that. For now you can install directly from github, then it should also work.

**Comment by HDembinski** [comment]
pyhepmc_ng works with Python2.7, no problem.

**Comment by HDembinski** [comment]
I just uploaded version 0.4.3 to PyPI where this should be fixed. Please let me know whether this works for you.

**Comment by lukasheinrich** [comment]
Yes, that works. Thanks a lot!

**Comment by HDembinski** [comment]
Thanks for using pyhepmc :)
